### PR TITLE
Ksagiyam/merge upstream

### PR DESCRIPTION
**Pull request by ksagiyam**
Firedrake will need https://github.com/firedrakeproject/firedrake/pull/2176

### CODE REVIEW

**Comment by balay** [comment]
@ksagiyam is this PR intended to be merged to petsc? If so can you resubmit it at gitlab?

**Comment by ksagiyam** [comment]
@balay This PR is merely to test Firedrake against the latest (now 2 day old) PETSc (we only update our PETSc fork when all Firedrake tests pass). Thanks anyway.

**Comment by balay** [comment]
Ok. I'm not sure how this PR is helping with firedrake workflow - its fine by me [as I now know that it should be ignored].

**Comment by ksagiyam** [comment]
I'm sorry. Just noticed that I targeted `petsc/main` instead of `firedrakeproject/petsc`. Closing this PR.

**Pull request closed without merging**
